services:
  my_postgres:
    image: 'postgres:latest'
    container_name: kraski_postgres_db
    restart: always
    environment:
      - 'POSTGRES_DB=kraski_database'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_data:

